# This is a basic workflow to help you get started with Actions

name: QA Custodian

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      testInput:
        description: the test input
        default: "manual_run"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-run-cloud-custodian:
    name: Run Cloud Custodian
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install python3-venv -y
          python3 -m venv custodian
          source custodian/bin/activate
          pip install c7n
          pip install c7n_azure
          pip install c7n_gcp
          pip install c7n-mailer
      - name: update yaml files with user reserved names
        env: 
          USER_KEYS: ctw
          DO_NOT_DELETE_KEYS: DO_NOT_DELETE
        run: | 
          date
          cd qa-custodian
          while read -r line; do export USER_KEYS="${USER_KEYS}|$line"; done < user-keys.txt
          for i in `ls *.yaml`; do cat $i | sed -e 's/USERKEYS/'"$USER_KEYS"'/g' -i $i; done
          while read -r line; do export DO_NOT_DELETE_KEYS="${DO_NOT_DELETE_KEYS}|$line"; done < do-not-delete-keys.txt
          for i in `ls *.yaml`; do cat $i | sed -e 's/DONOTDELETEKEYS/'"$DO_NOT_DELETE_KEYS"'/g' -i $i; done
      - name: run cloud custodian
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          source custodian/bin/activate
          cd qa-custodian
          cat nlb.yaml
          while read -r line; do custodian run --output-dir=. --region=$line --dry-run nlb.yaml; done < regions.txt
          while read -r line; do custodian run --output-dir=. --region=$line --dry-run instances.yaml; done < regions.txt
